// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeSanBox: typeof import('./src/components/CodeSanBox.vue')['default']
    DisplayCodeSanBox: typeof import('./src/components/DisplayCodeSanBox.vue')['default']
  }
}

export { }
